### PR TITLE
Budget app

### PR DESCRIPTION
**Pull request by GutemaG**
### Description
- Create a Ruby on Rails application that allows the user to:
> - register and log in, so that the data is private to them.
> - introduce new transactions associated with a category.
> - see the money spent on each category.

#### Interactions
- Splash screen
  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages
  - The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (categories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
    - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
## Hello @GutemaG  👋 🙂

You're doing a great job on your project. We're proud of you. Good job so far! 

It's OK to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job. 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of GitHub Flow
  ✅  Descriptive Pull Request
  ✅  No linter errors

## Required Changes ♻️

- [ ] When I try to create a group on the hosted version of the app. It shows the following error. Kindly fix that 👍 
Screenshot 2023-04-29 at 1 43 08 AM





## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GutemaG** [comment]
@zainsadaqat Thank you. The above problem is because of when you specify url to icons, it is not an image. ```The link should be an image link not random text```

**Comment by KDlamini** [comment]
> @zainsadaqat Thank you. The above problem is because of when you specify url to icons, it is not an image. `The link should be an image link not random text`

Well resolved ✔️ 



[OPTIONAL] I think it would be best to add specific width and height to all category images so that they all look uniform.

**Review by KDlamini — APPROVED** [review]
### Hi @GutemaG 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes for the Budget app. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Great PR title and description
✔️ Application UI follows all design guidelines
✔️ Models, Controllers, Views, and Routes well implemented
✔️ Unit tests and integration specs are well-written

# Status: Approved ✔️ 

oscars-standing-ovation

## Optional Suggestions

Next time please make sure that you follow the proper GitHub flow when submitting the final review for a Capstone project. This means that you must submit a PR merging the `dev` branch to the `main`. 
The `dev` branch is used for the `development stage` which is when you introduce different features that are merged to the `dev` branch. When the project is done, all the features that were implemented in the `development stage` must now be merged to the `main` branch (the `production stage`) in order to ready the project for `deployment`.

<hr />
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
